apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresql.database }}
  POSTGRES_USER: {{ .Values.postgresql.pyramid_keno_user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.pyramid_keno_password }}
