apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRES_DB: "kenodb"
  POSTGRES_USER: "keno_user"
  POSTGRES_PASSWORD: "keno_passw"
