apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{- include "postgresql.selectorLabels" . | nindent 4 }}
