name: ðŸš€ Manual CD - Deploy Backend

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag to deploy (e.g., latest or 123)'
        required: true
        type: string
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update image tag in values.yaml
        run: |
          echo "Deploying version ${{ github.event.inputs.version }}"
          sed -i "s/tag:.*/tag: \"${{ github.event.inputs.version }}\"/" \
            gitops/charts/backend/values.yaml

      - name: Commit and push update
        run: |
          git config user.name "suvorov"
          git config user.email "suvorov22002@gmail.com"
          git add gitops/charts/backend/values.yaml
          git commit -m "Deploy image version ${{ github.event.inputs.version }}"
          git push origin master